# Generated by Django 5.2 on 2025-05-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decante_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
    ]
