# Generated by Django 5.2 on 2025-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decante_app', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='abonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deudor',
            name='perfumes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
